apiVersion: v1
kind: ConfigMap
metadata:
  name: java-demo-configmap
data:
  application.properties: |-
    spring.datasource.url=jdbc:postgresql://tododb.tododb.svc.cluster.local:5432/todo
    spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    management.endpoints.web.exposure.include=*
    demo.env="I was deployed with fabric8"
